---
- name: enable sudo modular configuration
  lineinfile:
    dest: "/usr/local/etc/sudoers"
    line: "#includedir /usr/local/etc/sudoers.d"
    state: present
    validate: "visudo -cf %s"

- name: enable passwordless sudo for members of the wheel group
  copy:
    src: "files/sudoers-wheel"
    dest: "/usr/local/etc/sudoers.d/sudoers-wheel"
    mode: '0440'
